// THIS FILE IS GENERATED - DO NOT MODIFY
export const BUILD_FRAMEWORK_CLI_NAME = 'tnp';
export const PROJECT_NPM_NAME = 'taon-ui';
export const CURRENT_PACKAGE_VERSION = '0.0.1';
// THIS FILE IS GENERATED - DO NOT MODIFY
      